### ISSUE TITLE
TOML简介

### ISSUE THREAD

**Issue by bluezhan** [webBureau/Web-Front-End-Code-Snippet#1]
#### 起因

前段时间，老夏说要将我们的配置文件改成TOML格式；这让我想起之前看过关于项目配置文件的问题。

前几年GitHub将一些新项目转用CoffeeScript 来处理JavaScript。大家都知道CoffeeScript比JavaScript要简洁优雅得多了。同样地，GitHub也觉得YAML不够简洁优雅，需要对它动动手脚，因此捣鼓出了一个TOML来。

配置文件的使用由来已久，从.ini、XML、JSON、YAML再到TOML，语言的表达能力越来越强，同时书写便捷性也在不断提升。 

TOML是前GitHub CEO， Tom Preston-Werner，于2013年创建的语言，其目标是成为一个小规模的易于使用的语义化配置文件格式。TOML被设计为可以无二义性的转换为一个哈希表(Hash table)。

作者是 GitHub联合创始人Tom Preston-Werner ：因为我们需要一个像样的人类可读的格式，同时能无歧义地映射到哈希表。然后　YAML 的规范有 80 页那么长，真是发指！不，不考虑　JSON 。你知道为什么。

TOML的全称是Tom's Obvious, Minimal Language，因为它的作者是GitHub联合创始人Tom Preston-Werner 。

TOML 的目标是成为一个极简的配置文件格式。TOML 被设计成可以无歧义地被映射为哈希表，从而被多种语言解析。

#### TOML例子文件

```TOML
# 这是一个TOML文件

title = "TOML Example"

[owner]
name = "Lance Uppercut"
dob = 1979-05-27T07:32:00-08:00 # 日期是一等公民

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]
  #你可以使用空格、制表符进行缩进，或者根本不缩进。TOML不关心缩进。
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# 数组内可以混入换行符
hosts = [
  "alpha",
  "omega"
]
  
```

#### 参考详情阅读

[TOML： GitHub 这是要革 YAML 的命呀！](https://segmentfault.com/a/1190000000477752)

https://github.com/toml-lang/toml
